import { registerUiModule } from "../uiModuleRegistry.js";
import { escapeHtml } from "../utils/html.js";
const labels={sales_drop:"销售额下降",profit_drop:"利润下降",sales_gap:"销售断档",data_quality_issue:"数据质量问题"};const severityLabels={high:"高风险",medium:"需关注",low:"低风险"};
const money=(value)=>value===null||value===undefined?"暂无数据":`¥${Number(value).toLocaleString("zh-CN",{maximumFractionDigits:2})}`;
const change=(value)=>value===null||value===undefined?"—":`${(Number(value)*100).toFixed(1)}%`;
const itemKey=(item)=>[item.anomalyType,item.objectType,item.objectId].join("|");
function detail(item,canLaunch){const trend=item.trendSummary||{},standard=item.recommendedActionStandard;return `<article class="business-anomaly-detail"><header><div><p class="eyebrow">ANOMALY DETAIL</p><h3>${escapeHtml(labels[item.anomalyType]||item.anomalyType)}</h3><p>${escapeHtml(item.objectName||"未命名对象")}</p></div><span class="status-pill">${escapeHtml(severityLabels[item.severity])}</span></header><dl><div><dt>异常对象</dt><dd>${escapeHtml(item.objectType)} · ${escapeHtml(item.objectName||item.objectId)}</dd></div><div><dt>当前周期</dt><dd>${escapeHtml(item.currentPeriod?.startDate||"—")} 至 ${escapeHtml(item.currentPeriod?.endDate||"—")}</dd></div><div><dt>对比周期</dt><dd>${escapeHtml(item.comparePeriod?.startDate||"—")} 至 ${escapeHtml(item.comparePeriod?.endDate||"—")}</dd></div><div><dt>当前值</dt><dd>${money(item.currentValue)}</dd></div><div><dt>对比值</dt><dd>${money(item.compareValue)}</dd></div><div><dt>变化率</dt><dd>${change(item.changeRate)}</dd></div></dl>${standard?`<section class="business-anomaly-recommendation"><span>推荐行动标准</span><strong>${escapeHtml(standard.name)}</strong><small>标准目标：${escapeHtml(standard.target||"未维护")}</small><small>流程：${escapeHtml(standard.processName||"未配置")}</small></section>`:""}${item.trendSummary?`<section class="business-anomaly-trend"><h4>销售趋势摘要</h4><div><span>前7日销售额<strong>${money(trend.compareSalesAmount)}</strong></span><span>近7日销售额<strong>${money(trend.currentSalesAmount)}</strong></span><span>前7日利润<strong>${money(trend.compareProfitAmount)}</strong></span><span>近7日利润<strong>${money(trend.currentProfitAmount)}</strong></span></div></section>`:""}<footer><button type="button" class="secondary-button" data-anomaly-object="${escapeHtml(item.objectType)}" data-anomaly-id="${escapeHtml(item.objectId)}">查看对象详情</button>${canLaunch&&standard?`<button type="button" class="primary-button" data-launch-anomaly-action="${escapeHtml(itemKey(item))}">发起关键行动</button>`:""}<small>保存不会生成任务；仅在用户确认启动后按标准流程生成。</small></footer></article>`;}
export function renderBusinessAnomalies({state={}}={}){
 if(state.loading)return `<section class="business-anomalies"><div class="empty-state compact">正在发现经营异常…</div></section>`;
 if(state.error)return `<section class="business-anomalies"><div class="empty-state compact"><strong>异常分析暂不可用</strong><p>${escapeHtml(state.error)}</p></div></section>`;
 const data=state.data;if(!data?.hasData)return `<section class="business-anomalies"><div class="empty-state compact">暂无可分析的销售日报事实</div></section>`;
 const selected=data.items.find((item)=>itemKey(item)===state.selectedKey)||null;
 return `<section class="business-anomalies" data-module-key="business_anomalies"><header><div><p class="eyebrow">BUSINESS ANOMALIES V1</p><h2>经营异常</h2><p>系统只标记变化与断档，不判断业务原因</p></div><div class="business-anomaly-summary"><span>高风险<strong>${data.summary.high}</strong></span><span>需关注<strong>${data.summary.medium}</strong></span><span>全部<strong>${data.summary.total}</strong></span></div></header>${selected?detail(selected,state.canLaunch):""}<div class="business-anomaly-list">${data.items.length?data.items.map((item)=>`<button type="button" class="is-${escapeHtml(item.severity)} ${state.selectedKey===itemKey(item)?"is-selected":""}" data-anomaly-select="${escapeHtml(itemKey(item))}"><span class="status-pill">${escapeHtml(severityLabels[item.severity])}</span><div><strong>${escapeHtml(item.objectName||"未命名对象")}</strong><small>${escapeHtml(labels[item.anomalyType]||item.anomalyType)} · ${escapeHtml(item.objectType)}</small></div><div><strong>${item.anomalyType==="sales_gap"?`连续${item.gapDays}天无事实`:money(item.currentValue)}</strong><small>对比 ${money(item.compareValue)} · ${change(item.changeRate)}</small></div></button>`).join(""):`<div class="empty-state compact">当前规则下未发现异常</div>`}</div></section>`;
}
registerUiModule({moduleKey:"business_anomalies",name:"BusinessAnomalies",domain:"dashboard",description:"发现销售下降、利润下降、销售断档与数据质量异常，并提供人工发起关键行动入口。",dependencies:["QueryDailySalesSummary","QuerySalesDailyDataQuality","keyActions.launch"],configSchema:{},render:renderBusinessAnomalies});
