import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function setup(){const nodes=new Map();const get=s=>{if(!nodes.has(s))nodes.set(s,{addEventListener(){},elements:{scheduledAt:{value:''}}});return nodes.get(s);};const context=vm.createContext({document:{querySelector:get,querySelectorAll:()=>[]},window:{addEventListener(){}},console});vm.runInContext(readFileSync(new URL('../../public/content-center/app.js',import.meta.url),'utf8').replace(/init\(\);\s*$/,''),context);return{context,get,run:s=>vm.runInContext(s,context)};}
test('时间格覆盖凌晨和深夜、精确两小时边界、旧空时间',()=>{const {run}=setup();for(const [time,bucket] of [['00:00',0],['07:59',6],['08:00',8],['09:59',8],['10:00',10],['23:59',22],['',null],['24:00',null]])assert.equal(run(`timeBucket(${JSON.stringify(time)})`),bucket);});
test('格子拖动改日期与时间；月历只改日期；候选先打开表单不写数据',()=>{const {run,get}=setup();run("notes=[{id:'formal',pool:'schedule'},{id:'idea',pool:'candidate',productIds:['p'],templateId:'t',noteFormat:'视频'}]; var captured=null; patchNote=(id,patch)=>captured={id,patch}; openEditor=(n,date,pool)=>captured={n,date,pool};");const drop=(id,time)=>get('#workspace').ondrop({preventDefault(){},target:{closest(){return{dataset:{dropDate:'2026-09-20',...(time?{dropTime:time}:{})}};}},dataTransfer:{getData(){return id;}}});drop('formal','14:00');assert.equal(run('captured.patch.time'),'14:00');assert.equal(run('captured.patch.date'),'2026-09-20');drop('formal');assert.equal(run('captured.patch.time'),undefined);drop('idea','18:00');assert.equal(run('captured.pool'),'schedule');assert.equal(run('captured.n.productIds[0]'),'p');assert.equal(run('captured.n.templateId'),'t');assert.equal(get('#note-form').elements.scheduledAt.value,'2026-09-20T18:00');});
test('账号标签筛选、切换与取消，保留品牌状态并清空栏目',()=>{
 const {run,get}=setup();run("meta={accounts:[{id:'1',unitId:'brand'},{id:'2',unitId:'brand'}]};notes=[{id:'one',account:'1',pool:'schedule',status:'草稿'},{id:'two',account:'2',pool:'schedule',status:'草稿'}];filters={unit:'brand',account:'',column:'旧栏目',status:'草稿'};var renders=0;render=()=>renders++;");
 const click=id=>get('#workspace').onclick({target:{closest:()=>({dataset:{accountFilter:id},hasAttribute:key=>key==='data-account-filter'})}});
 click('1');assert.equal(run('filtered()[0].id'),'one');assert.equal(run('filtered().length'),1);assert.equal(run('filters.column'),'');assert.equal(run('filters.unit'),'brand');assert.equal(run('filters.status'),'草稿');
 click('2');assert.equal(run('filtered()[0].id'),'two');click('2');assert.equal(run('filters.account'),'');assert.equal(run('filtered().length'),2);assert.equal(run('renders'),3);
});
test('单条表单品牌账号栏目联动清空',()=>{const {run,get}=setup();run("meta={accounts:[{id:'1',unitId:'a',name:'甲',columns:[{name:'甲栏目'}]},{id:'2',unitId:'b',name:'乙',columns:[{name:'乙栏目'}]}]};");const f={unitId:{value:'b'},account:{value:'1'},column:{value:'甲栏目'}};const change=name=>get('#note-form').onchange({target:{name},currentTarget:{elements:f}});change('unitId');assert.equal(f.account.value,'');assert.equal(f.column.value,'');assert.equal(f.column.disabled,true);assert.match(f.account.innerHTML,/乙/);assert.doesNotMatch(f.account.innerHTML,/甲/);f.account.value='2';change('account');assert.equal(f.column.disabled,false);assert.match(f.column.innerHTML,/乙栏目/);});
