import crypto from "node:crypto";
import { createResource,getDatabase } from "./db.js";
const text=v=>String(v??"").trim(),now=()=>new Date().toISOString(),parse=(v,f)=>{try{return JSON.parse(v)}catch{return f}},id=p=>`${p}-${crypto.randomUUID()}`;
function pct(v){return v==null?"数据不足":`${(Number(v)*100).toFixed(1)}%`;}
function explain(type,e){const findings=[],suggestions=[],refs=[];const add=(severity,kind,title,evidence,source,actions)=>{findings.push({severity,type:kind,title,evidence,source});refs.push(source);for(const action of actions)suggestions.push({title:action,reason:title,requiresConfirmation:true});};
  if(type==="company"){const p=e.company?.products||{},c=e.company?.connections||{},r=e.company?.risks||{};if(p.salesGrowth!=null&&p.salesGrowth<-.1)add("high","sales","公司产品销量下降",`近两期30天销量变化 ${pct(p.salesGrowth)}`,"connection_sku_sales_daily_facts",["复盘销量下降产品并确定改善优先级"]);if(r.connectionRisk>0)add("high","connection",`${r.connectionRisk}个连接处于风险状态`,"来自连接经营体检","connection_health_records",["逐项确认风险连接原因与负责人"]);if(p.capitalOccupation>0&&p.capitalCoverage<1)add("medium","inventory","库存资金口径不完整",`成本覆盖率 ${pct(p.capitalCoverage)}`,"erp_sku_inventory_daily_summaries",["补齐ERP成本事实后再判断资金占用"]);if(c.payAmount==null)add("info","connection","连接经营数据不足","当前没有可用经营周期","connection_period_snapshots",["完成经营数据导入和连接映射"]);}
  if(type==="product"){if(e.sales?.growth!=null&&e.sales.growth<-.2)add("high","sales","产品销量明显下降",`销量变化 ${pct(e.sales.growth)}`,"connection_sku_sales_daily_facts",["复盘流量、转化和产品竞争力"]);if(e.inventory?.risk&&!["正常","暂无数据"].includes(e.inventory.risk))add("high","inventory",`产品${e.inventory.risk}`,`实际库存 ${e.inventory.actualStock??"未知"}`,"erp_sku_inventory_daily_summaries",[e.inventory.risk==="积压"?"制定库存去化行动":"检查补货与交付计划"]);if(e.finance?.profitMargin!=null&&e.finance.profitMargin<.1)add("high","profit","产品毛利偏低",`毛利率 ${pct(e.finance.profitMargin)}`,"connection_sku_sales_daily_facts",["复核销售成本与定价结构"]);}
  if(type==="connection"){if(e.salesGrowth!=null&&e.salesGrowth<-.2)add("high","sales","连接销售下降",`销售变化 ${pct(e.salesGrowth)}`,"connection_period_snapshots",["复盘连接流量与转化变化"]);if(e.visitorGrowth!=null&&e.visitorGrowth<-.2)add("medium","traffic","连接流量下降",`访客变化 ${pct(e.visitorGrowth)}`,"connection_period_snapshots",["检查搜索、推广和内容入口"]);if(e.conversionChange!=null&&e.conversionChange<-.01)add("high","conversion","连接转化下降",`转化下降 ${(Math.abs(e.conversionChange)*100).toFixed(1)}个百分点`,"connection_period_snapshots",["检查主图、详情、价格和评价"]);}
  if(type==="supply"){const s=e.summary||{};if(s.shortageCount>0)add("high","stockout",`${s.shortageCount}项缺货风险`,"低于安全库存","supplier_products + ERP snapshots",["检查补货计划和供应交期"]);if(s.backlogCount>0)add("medium","backlog",`${s.backlogCount}项积压风险`,"有库存但30天无销量","ERP snapshots",["制定库存去化方案"]);if(s.overduePurchaseCount>0)add("high","delivery",`${s.overduePurchaseCount}笔采购逾期`,"预计到货日已过","purchase_orders",["向供应商确认到货并更新计划"]);}
  if(type==="customer"){const s=e.summary||{};if(s.churnRiskCount>0)add("high","churn",`${s.churnRiskCount}位客户存在流失风险`,"最近消费超过90天","customers + customer_consumptions",["制定分层回访和维护计划"]);if(!s.customerCount)add("info","data","客户事实不足","当前客户数量为0","customers",["先建立客户档案与消费事实"]);}
  if(type==="finance"){const s=e.summary||{};if(s.netProfit<0)add("critical","profit","经营净利润为负",`净利润 ${s.netProfit}`,"finance_entries",["拆解收入、成本和费用变动"]);if(s.profitMargin!=null&&s.profitMargin<.1)add("high","margin","经营利润率偏低",`利润率 ${pct(s.profitMargin)}`,"finance_entries",["按产品、链接和费用科目定位原因"]);}
  if(e.knowledge?.actionStandards?.length){refs.push("task_templates");if(suggestions.length)suggestions.push({title:"执行前选择匹配的现有行动标准",reason:`已有 ${e.knowledge.actionStandards.length} 个启用标准可供人工选择`,requiresConfirmation:true,knowledgeType:"action_standard"});}
  if(e.knowledge?.effectiveImprovements?.length){refs.push("connection_improvements","product_improvements");if(suggestions.length)suggestions.push({title:"参考同类历史有效改善记录",reason:`检索到 ${e.knowledge.effectiveImprovements.length} 条已验证结果，需人工判断是否适用`,requiresConfirmation:true,knowledgeType:"verified_improvement"});}
  if(!findings.length)findings.push({severity:"info",type:"stable",title:"当前未触发明确风险规则",evidence:"可用事实未达到预警阈值",source:"verified_business_facts"});return{findings,suggestions,refs:[...new Set(refs)]};}
function normalize(row){return row?{...row,sourceSnapshot:parse(row.sourceSnapshotJson,{}),sourceReferences:parse(row.sourceReferencesJson,[]),findings:parse(row.findingsJson,[]),suggestions:parse(row.suggestionsJson,[])}:null;}
export function createAnalysis(input,userId,evidence){const type=text(input.analysisType);if(!["company","product","connection","finance","supply","customer"].includes(type))throw new Error("分析类型无效。");if(!evidence||typeof evidence!=="object")throw new Error("没有可追溯的经营事实，不能生成分析。");const result=explain(type,evidence),ts=now(),key=id("ai-analysis"),title=text(input.title)||`${({company:"公司经营",product:"产品经营",connection:"连接经营",finance:"财务经营",supply:"供应链",customer:"客户经营"})[type]}分析`;
  getDatabase().prepare(`INSERT INTO ai_analysis_records(id,analysisType,objectType,objectId,title,question,providerMode,ruleVersion,sourceSnapshotJson,sourceReferencesJson,findingsJson,suggestionsJson,status,generatedBy,createdAt,updatedAt) VALUES(?,?,?,?,?,?, 'explainable_rules','v1',?,?,?,?, 'draft',?,?,?)`).run(key,type,text(input.objectType)||type,text(input.objectId)||null,title,text(input.question),JSON.stringify(evidence),JSON.stringify(result.refs),JSON.stringify(result.findings),JSON.stringify(result.suggestions),userId,ts,ts);return normalize(getDatabase().prepare("SELECT * FROM ai_analysis_records WHERE id=?").get(key));}
export function listAnalyses(userId,all=false){return getDatabase().prepare(`SELECT * FROM ai_analysis_records ${all?"":"WHERE generatedBy=?"} ORDER BY createdAt DESC LIMIT 100`).all(...(all?[]:[userId])).map(normalize);}
export function readAnalysis(key){const row=normalize(getDatabase().prepare("SELECT * FROM ai_analysis_records WHERE id=?").get(text(key)));if(!row)throw new Error("分析记录不存在。");return row;}
export function confirmAnalysis(key,userId){const db=getDatabase(),row=readAnalysis(key);if(row.status!=="draft")throw new Error("该分析已经确认或转入行动。");db.prepare("UPDATE ai_analysis_records SET status='confirmed',confirmedBy=?,confirmedAt=?,updatedAt=? WHERE id=?").run(userId,now(),now(),row.id);return readAnalysis(row.id);}
export function createAnalysisAction(key,input,userId){const db=getDatabase(),row=readAnalysis(key);if(row.status!=="confirmed")throw new Error("请先人工确认分析结果。");const goal=db.prepare("SELECT id FROM goals WHERE id=? AND status='active'").get(text(input.goalId));if(!goal)throw new Error("请选择有效目标。");const template=db.prepare(`SELECT t.id,t.defaultProcessTemplateId,p.version FROM task_templates t JOIN process_templates p ON p.id=t.defaultProcessTemplateId WHERE t.id=? AND t.status='active'`).get(text(input.taskTemplateId));if(!template)throw new Error("请选择已绑定标准流程的启用关键行动。");return db.transaction(()=>{const ts=now(),title=text(input.title)||`改善：${row.title}`;const instance=createResource("process-instances",{id:id("process-instance"),templateId:template.defaultProcessTemplateId,taskTemplateId:template.id,templateVersion:template.version,name:title,displayTitle:title,goalId:goal.id,initiatorId:userId,description:`来源：AI经营助手；分析记录：${row.id}`,status:"draft",customFields:{source:"ai_operation_assistant",aiAnalysisId:row.id,analysisType:row.analysisType,objectId:row.objectId},createdAt:ts,updatedAt:ts});db.prepare("UPDATE ai_analysis_records SET status='action_created',actionId=?,updatedAt=? WHERE id=?").run(instance.id,ts,row.id);return{analysis:readAnalysis(row.id),instance};})();}
