import { getDatabase } from "./db.js";
import { listConnectionGrowthAnalyses } from "./connectionGrowthService.js";
import { readConnectionV3MetricsMap } from "./connectionV3MetricsService.js";

function text(value) { return String(value ?? "").trim(); }
function ratio(current, previous) { return previous ? (current - previous) / previous : null; }
function periodType(start, end) { const days = Math.round((Date.parse(end) - Date.parse(start)) / 86400000) + 1; return days <= 1 ? "day" : days <= 7 ? "week" : "month"; }

export function getConnectionBusinessCockpit(userId = "", isAdmin = false) {
  const database = getDatabase(); const personId = text(userId);
  const profiles = database.prepare(`
    SELECT c.id,c.salesLinkId,c.name,c.mainImage,c.ownerId,c.status,c.createdAt,
      l.platformGoodsId,s.platform,s.id shopId,COALESCE(s.displayName,s.shopName) shopName
    FROM connection_profiles c JOIN sales_links l ON l.id=c.salesLinkId JOIN sales_shops s ON s.id=l.shopId
    ${isAdmin ? "" : "WHERE c.ownerId=?"} ORDER BY c.updatedAt DESC,c.id DESC
  `).all(...(isAdmin ? [] : [personId]));
  const connectionIds = profiles.map((item) => item.id); const salesLinkIds = profiles.map((item) => item.salesLinkId);
  if (!profiles.length) return emptyCockpit();
  const placeholders = connectionIds.map(() => "?").join(","); const linkPlaceholders = salesLinkIds.map(() => "?").join(",");
  const metrics = readConnectionV3MetricsMap(salesLinkIds);
  const connectionIdSet = new Set(connectionIds);
  const analyses = new Map(listConnectionGrowthAnalyses().filter((item) => connectionIdSet.has(item.connectionId)).map((item) => [item.connectionId, item]));
  const productRows = database.prepare(`SELECT c.id connectionId,p.id,p.skuCode,p.name,p.mainImage FROM connection_profiles c JOIN sales_link_skus s ON s.salesLinkId=c.salesLinkId JOIN products p ON p.id=s.productId WHERE c.id IN (${placeholders}) AND COALESCE(s.currentState,'active')='active' GROUP BY c.id,p.id,p.skuCode,p.name,p.mainImage ORDER BY p.skuCode`).all(...connectionIds);
  const productsByConnection = new Map(); for (const row of productRows) { const rows = productsByConnection.get(row.connectionId) ?? []; rows.push(row); productsByConnection.set(row.connectionId, rows); }
  const diagnosis = new Set(database.prepare(`SELECT connectionId FROM connection_diagnosis_entries WHERE connectionId IN (${placeholders}) AND status='active'`).all(...connectionIds).map((row) => row.connectionId));
  const improvements = database.prepare(`SELECT connectionId,status FROM connection_improvements WHERE connectionId IN (${placeholders}) ORDER BY updatedAt DESC,createdAt DESC`).all(...connectionIds);
  const improvementByConnection = new Map(); for (const row of improvements) if (!improvementByConnection.has(row.connectionId) && !["effective","closed"].includes(row.status)) improvementByConnection.set(row.connectionId, row.status);
  const items = profiles.map((profile) => { const v3 = metrics.get(profile.salesLinkId); const analysis = analyses.get(profile.id) ?? {}; const salesGrowth = v3.salesGrowth ?? analysis.salesGrowth ?? null; const profitGrowth = v3.profitGrowth ?? analysis.profitGrowth ?? null; const improvement = improvementByConnection.get(profile.id); const operationStage = improvement === "executing" ? "treatment" : improvement === "observing" ? "observation" : diagnosis.has(profile.id) || ["planned","failed"].includes(improvement) ? "diagnosis" : "normal"; const healthStatus = analysis.healthStatus ?? "no_data"; const risk = healthStatus === "risk" || healthStatus === "attention" || Number(salesGrowth) < -0.2 || Number(profitGrowth) < -0.2 || Number(analysis.visitorGrowth) < -0.2 || Number(analysis.conversionChange) < -0.01; return { ...profile, products: productsByConnection.get(profile.id) ?? [], erpSales: v3.current, previousErpSales: v3.previous, platformPerformance: v3.platform, salesGrowth, profitGrowth, visitorGrowth: analysis.visitorGrowth ?? null, conversionChange: analysis.conversionChange ?? null, healthScore: analysis.healthScore ?? null, healthStatus, operationStage, risk }; });
  const totalSales = items.reduce((sum, item) => sum + Number(item.erpSales.salesAmount || 0), 0); const totalProfit = items.reduce((sum, item) => sum + Number(item.erpSales.profitAmount || 0), 0); const previousSales = items.reduce((sum, item) => sum + Number(item.previousErpSales?.salesAmount || 0), 0); const shippedQuantity = items.reduce((sum, item) => sum + Number(item.erpSales.shippedQuantity || 0), 0);
  const currentPeriods = items.filter((item) => item.erpSales.periodStart && item.erpSales.periodEnd).map((item) => ({ start: item.erpSales.periodStart, end: item.erpSales.periodEnd, updatedAt: item.erpSales.updatedAt }));
  const periodKeys = new Set(currentPeriods.map((item) => `${item.start}|${item.end}`));
  const salesPeriodStart = currentPeriods.map((item) => item.start).sort()[0] ?? null;
  const salesPeriodEnd = currentPeriods.map((item) => item.end).sort().at(-1) ?? null;
  const salesUpdatedAt = currentPeriods.map((item) => item.updatedAt).filter(Boolean).sort().at(-1) ?? null;
  const health = { healthy: 0, attention: 0, risk: 0, noData: 0 };
  for (const item of items) {
    if (["no_data","insufficient_data"].includes(item.healthStatus)) health.noData += 1;
    else if (item.healthStatus === "risk" || Number(item.salesGrowth) < -0.2 || Number(item.profitGrowth) < -0.2 || Number(item.visitorGrowth) < -0.2 || Number(item.conversionChange) < -0.01) health.risk += 1;
    else if (item.healthStatus === "attention") health.attention += 1;
    else health.healthy += 1;
  }
  const coreLinks = items.filter((item) => item.erpSales.periodEnd).sort((a,b) => Number(b.erpSales.salesAmount||0)-Number(a.erpSales.salesAmount||0) || Number(b.erpSales.profitAmount||0)-Number(a.erpSales.profitAmount||0) || Number(b.erpSales.shippedQuantity||0)-Number(a.erpSales.shippedQuantity||0)).slice(0,10);
  const riskLinks = items.filter((item) => item.risk).sort((a,b) => Number(a.healthScore??101)-Number(b.healthScore??101) || Number(a.salesGrowth??0)-Number(b.salesGrowth??0)).slice(0,10).map((item) => ({ ...item, anomalyTypes: [Number(item.salesGrowth)<-0.2?"销售下降":"",Number(item.profitGrowth)<-0.2?"利润下降":"",Number(item.visitorGrowth)<-0.2?"流量下降":"",Number(item.conversionChange)<-0.01?"转化下降":""].filter(Boolean) }));
  const growthLinks = items.map((item) => ({ ...item, growthMetric: Math.max(...[item.salesGrowth,item.profitGrowth,item.visitorGrowth,item.conversionChange].filter((value) => value !== null).map(Number), -Infinity) })).filter((item) => Number.isFinite(item.growthMetric) && item.growthMetric > 0).sort((a,b) => b.growthMetric-a.growthMetric).slice(0,10);
  const platformMap = new Map(); for (const item of items) { const row=platformMap.get(item.platform)??{platform:item.platform,connectionCount:0,salesAmount:0,profitAmount:0,riskCount:0,healthyCount:0}; row.connectionCount++; row.salesAmount+=Number(item.erpSales.salesAmount||0); row.profitAmount+=Number(item.erpSales.profitAmount||0); if(item.risk)row.riskCount++; if(["growing","stable"].includes(item.healthStatus)&&!item.risk)row.healthyCount++; platformMap.set(item.platform,row); }
  const platforms=[...platformMap.values()].map((row)=>({...row,profitMargin:row.salesAmount?row.profitAmount/row.salesAmount:null,healthyRate:row.connectionCount?row.healthyCount/row.connectionCount:0})).sort((a,b)=>b.salesAmount-a.salesAmount);
  const factRows=database.prepare(`SELECT f.salesLinkId,f.periodStart,f.periodEnd,f.salesAmount,f.profitAmount,s.productId,sh.platform FROM connection_sku_sales_facts f JOIN sales_link_skus s ON s.id=f.salesLinkSkuId JOIN sales_links l ON l.id=f.salesLinkId JOIN sales_shops sh ON sh.id=l.shopId WHERE f.salesLinkId IN (${linkPlaceholders}) AND s.productId IS NOT NULL`).all(...salesLinkIds);
  const latestKeys=new Map(items.map((item)=>[item.salesLinkId,`${item.erpSales.periodStart}|${item.erpSales.periodEnd}`])); const productChannelMap=new Map(); for(const row of factRows){if(`${row.periodStart}|${row.periodEnd}`!==latestKeys.get(row.salesLinkId))continue; const key=`${row.productId}|${row.platform}`; const current=productChannelMap.get(key)??{productId:row.productId,platform:row.platform,salesAmount:0,profitAmount:0,linkIds:new Set()}; current.salesAmount+=Number(row.salesAmount||0);current.profitAmount+=Number(row.profitAmount||0);current.linkIds.add(row.salesLinkId);productChannelMap.set(key,current);} const productMeta=new Map(productRows.map((row)=>[row.id,{skuCode:row.skuCode,name:row.name,mainImage:row.mainImage}])); const totalsByProduct=new Map(); for(const row of productChannelMap.values())totalsByProduct.set(row.productId,(totalsByProduct.get(row.productId)||0)+row.salesAmount); const productChannels=[...productChannelMap.values()].map((row)=>({productId:row.productId,...productMeta.get(row.productId),platform:row.platform,salesAmount:row.salesAmount,profitAmount:row.profitAmount,linkCount:row.linkIds.size,contribution:totalsByProduct.get(row.productId)?row.salesAmount/totalsByProduct.get(row.productId):0})).sort((a,b)=>b.salesAmount-a.salesAmount).slice(0,30);
  const erpTrend=database.prepare(`SELECT periodStart,periodEnd,SUM(COALESCE(shippedQuantity,0)) shippedQuantity,SUM(COALESCE(salesAmount,0)) salesAmount,SUM(COALESCE(profitAmount,0)) profitAmount FROM connection_sku_sales_facts WHERE salesLinkId IN (${linkPlaceholders}) GROUP BY periodStart,periodEnd ORDER BY periodEnd,periodStart`).all(...salesLinkIds).map((row)=>({...row,periodType:periodType(row.periodStart,row.periodEnd)}));
  const platformTrend=database.prepare(`SELECT periodStart,periodEnd,SUM(COALESCE(visitorCount,0)) visitorCount,SUM(COALESCE(viewCount,0)) viewCount FROM connection_period_snapshots WHERE salesLinkId IN (${linkPlaceholders}) GROUP BY periodStart,periodEnd ORDER BY periodEnd,periodStart`).all(...salesLinkIds).map((row)=>({...row,periodType:periodType(row.periodStart,row.periodEnd)}));
  return { summary:{connectionCount:items.length,normalCount:items.filter((item)=>!item.risk&&item.operationStage==="normal").length,riskCount:items.filter((item)=>item.risk).length,diagnosisCount:items.filter((item)=>item.operationStage==="diagnosis").length,treatmentCount:items.filter((item)=>item.operationStage==="treatment").length,observationCount:items.filter((item)=>item.operationStage==="observation").length,shippedQuantity,salesAmount:totalSales,salesGrowth:ratio(totalSales,previousSales),salesPeriodStart,salesPeriodEnd,salesPeriodAligned:periodKeys.size<=1,salesPeriodCount:periodKeys.size,salesUpdatedAt,profitAmount:totalProfit,profitMargin:totalSales?totalProfit/totalSales:null,highProfitCount:items.filter((item)=>Number(item.erpSales.profitMargin)>=0.2).length,profitRiskCount:items.filter((item)=>Number(item.erpSales.profitAmount)<0||Number(item.profitGrowth)<-0.2).length},health,coreLinks,riskLinks,growthLinks,platforms,productChannels,trends:{erp:erpTrend,platform:platformTrend},scope:{isAdmin:Boolean(isAdmin),ownerId:isAdmin?null:personId}};
}

function emptyCockpit(){return{summary:{},health:{healthy:0,attention:0,risk:0,noData:0},coreLinks:[],riskLinks:[],growthLinks:[],platforms:[],productChannels:[],trends:{erp:[],platform:[]},scope:{}};}
