import {
  addSupplierProductRelation, createSupplyPurchase, createSupplyQualityIssue, deleteSupplierProductRelation,
  getCurrentUser, loadSupplier, loadSuppliers, loadSupplyChainOverview, saveSupplyEvaluation,
  saveSupplierProfile, updateSupplyPurchase, updateSupplyQualityIssue,
} from "./appState.js";
import { hasPermission } from "./permissions.js";

let activeTab = "overview";
let loading = false;
let error = "";
let overview = null;
let suppliers = [];
let selected = null;
let products = [];
let mappings = [];
let filters = { search: "", status: "" };

const html = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[c]);
const number = (value, digits = 0) => value === null || value === undefined ? "—" : Number(value).toLocaleString("zh-CN", { maximumFractionDigits: digits });
const money = (value) => value === null || value === undefined ? "—" : `¥${number(value, 2)}`;
const statusName = (value) => ({ active: "合作中", paused: "暂停", archived: "归档", draft: "草稿", planned: "计划中", ordered: "已下单", partial: "部分到货", received: "已到货", canceled: "已取消", open: "待处理", improving: "改善中", resolved: "已解决", closed: "已关闭" })[value] || value || "—";
const canManage = () => hasPermission(getCurrentUser(), "supplyChain.manage");
const canPurchase = () => hasPermission(getCurrentUser(), "supplyChain.purchase");
const canQuality = () => hasPermission(getCurrentUser(), "supplyChain.quality");

function summary() {
  const item = overview?.summary || {};
  return `<div class="supply-summary">${[["供应商",item.activeSupplierCount,"正常合作"],["缺货风险",item.shortageCount,"低于安全库存"],["积压风险",item.backlogCount,"有库存但30天无销量"],["逾期采购",item.overduePurchaseCount,"未按期到货"],["品质问题",item.openQualityCount,"待处理或改善中"]].map(([label,value,note]) => `<article><span>${label}</span><strong>${number(value)}</strong><small>${note}</small></article>`).join("")}</div>`;
}

function overviewPanel() {
  const performance = overview?.supplierPerformance || [];
  const risks = overview?.risks || [];
  return `${summary()}<div class="supply-grid"><section class="supply-panel"><header><h2>供应风险</h2><p>库存事实日期 ${html(overview?.summary?.businessDate || "暂无")}</p></header><div class="supply-risk-list">${risks.length ? risks.slice(0,20).map((risk) => `<article><strong>${risk.type === "shortage" ? "缺货" : "积压"}</strong><span>当前 ${number(risk.actualStock)} · 安全 ${number(risk.safetyStock)} · 30天销量 ${number(risk.sales30d)}</span></article>`).join("") : `<div class="empty-state compact">暂无供应风险</div>`}</div></section><section class="supply-panel"><header><h2>供应商表现</h2><p>按最近综合评价排序</p></header><div class="supply-ranking">${performance.length ? performance.map((supplier,index) => `<button data-open-supplier="${html(supplier.id)}"><span>${index+1}</span><strong>${html(supplier.name)}</strong><em>${number(supplier.latestScore,1)}分</em></button>`).join("") : `<div class="empty-state compact">暂无评价数据</div>`}</div></section></div>`;
}

function suppliersPanel() {
  return `<section class="supply-panel"><header class="supply-toolbar"><div><h2>供应商档案</h2><p>${number(suppliers.length)} 家供应商</p></div><form data-supplier-filter><input name="search" value="${html(filters.search)}" placeholder="搜索名称或编码"/><select name="status"><option value="">全部状态</option><option value="active" ${filters.status==="active"?"selected":""}>合作中</option><option value="paused" ${filters.status==="paused"?"selected":""}>暂停</option></select><button class="secondary-button">筛选</button></form>${canManage()?`<button class="primary-button" data-action="new-supplier">新增供应商</button>`:""}</header><div class="table-wrap"><table class="data-table"><thead><tr><th>编码</th><th>供应商</th><th>联系人</th><th>供应产品</th><th>未结采购</th><th>品质问题</th><th>评价</th><th>状态</th></tr></thead><tbody>${suppliers.length ? suppliers.map((item)=>`<tr data-open-supplier="${html(item.id)}"><td>${html(item.code)}</td><td><button class="text-button">${html(item.name)}</button></td><td>${html(item.contactName||"—")}</td><td>${number(item.productCount)}</td><td>${number(item.openPurchaseCount)}</td><td>${number(item.openQualityCount)}</td><td>${item.latestScore===null?"—":`${number(item.latestScore,1)}分`}</td><td>${statusName(item.status)}</td></tr>`).join("") : `<tr><td colspan="8" class="empty-cell">暂无供应商</td></tr>`}</tbody></table></div></section>`;
}

function supplierForm(item = {}) { return `<form data-supplier-form class="supply-form"><input type="hidden" name="id" value="${html(item.id)}"/><label>供应商编码<input name="code" required value="${html(item.code)}"/></label><label>供应商名称<input name="name" required value="${html(item.name)}"/></label><label>联系人<input name="contactName" value="${html(item.contactName)}"/></label><label>联系电话<input name="contactPhone" value="${html(item.contactPhone)}"/></label><label>邮箱<input name="contactEmail" value="${html(item.contactEmail)}"/></label><label>状态<select name="status"><option value="active">合作中</option><option value="paused" ${item.status==="paused"?"selected":""}>暂停</option><option value="archived" ${item.status==="archived"?"selected":""}>归档</option></select></label><label class="span-2">地址<input name="address" value="${html(item.address)}"/></label><label class="span-2">备注<textarea name="notes">${html(item.notes)}</textarea></label><button class="primary-button">保存档案</button></form>`; }

function productOptions() { return products.map((p)=>`<option value="${html(p.id)}">${html(p.skuCode)} · ${html(p.name)}</option>`).join(""); }
function detailProducts(detail) { return `<div class="table-wrap"><table class="data-table"><thead><tr><th>产品编码</th><th>产品</th><th>ERP规格</th><th>成本</th><th>库存/安全库存</th><th>风险</th>${canManage()?"<th>操作</th>":""}</tr></thead><tbody>${detail.products.length ? detail.products.map((row)=>`<tr><td>${html(row.skuCode)}</td><td>${html(row.productName)}</td><td>${html(row.merchantSkuCode||row.specificationName||"—")}</td><td>${money(row.unitCost)}</td><td>${number(row.inventory.actualStock)} / ${number(row.inventory.safetyStock)}</td><td>${({shortage:"缺货",backlog:"积压",healthy:"健康",no_data:"暂无事实"})[row.inventory.risk]}</td>${canManage()?`<td><button class="text-button danger-text" data-delete-relation="${html(row.id)}">移除</button></td>`:""}</tr>`).join(""):`<tr><td colspan="7" class="empty-cell">暂无合作产品</td></tr>`}</tbody></table></div>${canManage()?`<form data-relation-form class="supply-form compact"><label>产品<select name="productId" required><option value="">选择产品</option>${productOptions()}</select></label><label>ERP规格<select name="productErpMappingId"><option value="">产品级关系</option>${mappings.map((m)=>`<option value="${html(m.id)}" data-product="${html(m.productId)}">${html(m.merchantSkuCode)} · ${html(m.specificationName)}</option>`).join("")}</select></label><label>供应成本<input name="unitCost" type="number" step="0.01"/></label><label>安全库存<input name="safetyStock" type="number" step="1"/></label><label>交期（天）<input name="leadTimeDays" type="number" step="1"/></label><button class="primary-button">关联产品</button></form>`:""}`; }

function detailPurchases(detail) { return `<div class="table-wrap"><table class="data-table"><thead><tr><th>采购编号</th><th>类型</th><th>数量</th><th>金额</th><th>预计到货</th><th>状态</th>${canPurchase()?"<th>更新</th>":""}</tr></thead><tbody>${detail.orders.length?detail.orders.map((row)=>`<tr><td>${html(row.businessCode)}</td><td>${html(row.orderType)}</td><td>${number(row.totalQuantity)}</td><td>${money(row.totalAmount)}</td><td>${html(row.expectedAt||"—")}</td><td>${statusName(row.status)}</td>${canPurchase()?`<td><select data-purchase-status="${html(row.id)}"><option value="planned">计划中</option><option value="ordered">已下单</option><option value="partial">部分到货</option><option value="received">已到货</option><option value="canceled">取消</option></select></td>`:""}</tr>`).join(""):`<tr><td colspan="7" class="empty-cell">暂无采购记录</td></tr>`}</tbody></table></div>${canPurchase()?`<form data-purchase-form class="supply-form compact"><label>类型<select name="orderType"><option value="demand">采购需求</option><option value="plan">采购计划</option><option value="purchase">采购记录</option></select></label><label>产品<select name="productId" required>${productOptions()}</select></label><label>数量<input name="quantity" type="number" min="1" required/></label><label>单价<input name="unitCost" type="number" min="0" step="0.01"/></label><label>预计到货<input name="expectedAt" type="date"/></label><button class="primary-button">创建采购</button></form>`:""}`; }

function detailQuality(detail) { return `<div class="supply-records">${detail.qualityIssues.length?detail.qualityIssues.map((row)=>`<article><div><strong>${html(row.title)}</strong><small>${html(row.productName||"供应商级")}</small></div><span>${html(row.severity)} · ${statusName(row.status)}</span>${canQuality()&&!["resolved","closed"].includes(row.status)?`<button class="text-button" data-resolve-quality="${html(row.id)}">标记解决</button>`:""}</article>`).join(""):`<div class="empty-state compact">暂无品质问题</div>`}</div>${canQuality()?`<form data-quality-form class="supply-form compact"><label>问题标题<input name="title" required/></label><label>关联产品<select name="productId"><option value="">供应商级</option>${productOptions()}</select></label><label>严重程度<select name="severity"><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="critical">严重</option></select></label><label class="span-2">问题描述<input name="description"/></label><button class="primary-button">记录问题</button></form>`:""}`; }

function detailEvaluations(detail) { return `<div class="supply-records">${detail.evaluations.length?detail.evaluations.map((row)=>`<article><div><strong>${number(row.totalScore,1)} 分</strong><small>${html(row.periodStart)} 至 ${html(row.periodEnd)}</small></div><span>成本 ${number(row.costScore)} · 交付 ${number(row.deliveryScore)} · 品质 ${number(row.qualityScore)} · 配合 ${number(row.cooperationScore)}</span></article>`).join(""):`<div class="empty-state compact">暂无评价</div>`}</div>${canManage()?`<form data-evaluation-form class="supply-form compact"><label>周期开始<input name="periodStart" type="date" required/></label><label>周期结束<input name="periodEnd" type="date" required/></label>${["costScore","deliveryScore","qualityScore","cooperationScore"].map((key,i)=>`<label>${["成本","交付","品质","配合"][i]}<input name="${key}" type="number" min="0" max="100" required/></label>`).join("")}<label class="span-2">备注<input name="notes"/></label><button class="primary-button">保存评价</button></form>`:""}`; }

function detailPanel() { const detail=selected; if(!detail)return ""; const supplier=detail.supplier; const tabs=[["profile","基础资料"],["products","合作产品"],["purchases","采购记录"],["quality","品质记录"],["evaluations","供应评价"]]; const content=activeTab==="profile"?(canManage()?supplierForm(supplier):`<div class="supply-profile"><strong>${html(supplier.name)}</strong><span>${html(supplier.contactName||"—")} · ${html(supplier.contactPhone||"—")}</span><p>${html(supplier.address||"暂无地址")}</p></div>`):activeTab==="products"?detailProducts(detail):activeTab==="purchases"?detailPurchases(detail):activeTab==="quality"?detailQuality(detail):detailEvaluations(detail); return `<section class="supply-detail"><header><button class="text-button" data-action="back-suppliers">← 返回供应商</button><div><h2>${html(supplier.name)}</h2><p>${html(supplier.code)} · ${statusName(supplier.status)}</p></div></header><nav class="subtabs">${tabs.map(([key,label])=>`<button class="${activeTab===key?"is-active":""}" data-supply-tab="${key}">${label}</button>`).join("")}</nav>${content}</section>`; }

export function renderSupplyChainCenterPage() { const body=loading?`<div class="form-note">正在读取供应链数据…</div>`:error?`<div class="form-error">${html(error)}</div>`:selected?detailPanel():activeTab==="suppliers"?suppliersPanel():overviewPanel(); return `<section class="supply-chain-page"><div class="section-heading"><div><h1>供应链中心</h1><p>供应商 → 产品 → 采购 → 库存 → 品质 → 供应评价</p></div></div>${selected?"":`<nav class="subtabs"><button class="${activeTab==="overview"?"is-active":""}" data-supply-tab="overview">供应链首页</button><button class="${activeTab==="suppliers"?"is-active":""}" data-supply-tab="suppliers">供应商管理</button></nav>`}${body}</section>`; }

async function refresh(rerender) { loading=true;error="";rerender();try{const [o,s]=await Promise.all([loadSupplyChainOverview(),loadSuppliers(filters)]);overview=o;suppliers=s.items||[];products=o.moduleData?.products||[];mappings=o.moduleData?.productErpMappings||[];}catch(e){error=e.message||"供应链中心读取失败。";}loading=false;rerender(); }
async function reloadSelected(rerender){if(!selected)return;selected=(await loadSupplier(selected.supplier.id)).detail;rerender();}
function values(form){return Object.fromEntries(new FormData(form));}
export function bindSupplyChainCenterPageEvents(rerender) {
  if(!overview&&!loading)refresh(rerender);
  document.querySelectorAll("[data-supply-tab]").forEach((button)=>button.addEventListener("click",()=>{activeTab=button.dataset.supplyTab;rerender();}));
  document.querySelectorAll("[data-open-supplier]").forEach((node)=>node.addEventListener("click",async()=>{try{selected=(await loadSupplier(node.dataset.openSupplier)).detail;activeTab="profile";rerender();}catch(e){error=e.message;rerender();}}));
  document.querySelector("[data-action='back-suppliers']")?.addEventListener("click",()=>{selected=null;activeTab="suppliers";rerender();});
  document.querySelector("[data-action='new-supplier']")?.addEventListener("click",()=>{selected={supplier:{status:"active"},products:[],orders:[],qualityIssues:[],evaluations:[]};activeTab="profile";rerender();});
  document.querySelector("[data-supplier-filter]")?.addEventListener("submit",async(e)=>{e.preventDefault();filters=values(e.currentTarget);await refresh(rerender);});
  document.querySelector("[data-supplier-form]")?.addEventListener("submit",async(e)=>{e.preventDefault();try{const data=values(e.currentTarget);const result=await saveSupplierProfile(data,data.id);selected=(await loadSupplier(result.item.id)).detail;await refresh(rerender);selected=(await loadSupplier(result.item.id)).detail;activeTab="profile";rerender();}catch(ex){error=ex.message;rerender();}});
  document.querySelector("[data-relation-form]")?.addEventListener("submit",async(e)=>{e.preventDefault();try{await addSupplierProductRelation(selected.supplier.id,values(e.currentTarget));await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}});
  document.querySelectorAll("[data-delete-relation]").forEach((button)=>button.addEventListener("click",async()=>{try{await deleteSupplierProductRelation(selected.supplier.id,button.dataset.deleteRelation);await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}}));
  document.querySelector("[data-purchase-form]")?.addEventListener("submit",async(e)=>{e.preventDefault();const data=values(e.currentTarget);try{await createSupplyPurchase({supplierId:selected.supplier.id,orderType:data.orderType,expectedAt:data.expectedAt,items:[{productId:data.productId,quantity:data.quantity,unitCost:data.unitCost}]});await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}});
  document.querySelectorAll("[data-purchase-status]").forEach((select)=>select.addEventListener("change",async()=>{try{await updateSupplyPurchase(select.dataset.purchaseStatus,{status:select.value});await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}}));
  document.querySelector("[data-quality-form]")?.addEventListener("submit",async(e)=>{e.preventDefault();try{await createSupplyQualityIssue({supplierId:selected.supplier.id,...values(e.currentTarget)});await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}});
  document.querySelectorAll("[data-resolve-quality]").forEach((button)=>button.addEventListener("click",async()=>{try{await updateSupplyQualityIssue(button.dataset.resolveQuality,{status:"resolved",resultSummary:"已完成改善并关闭问题"});await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}}));
  document.querySelector("[data-evaluation-form]")?.addEventListener("submit",async(e)=>{e.preventDefault();try{await saveSupplyEvaluation({supplierId:selected.supplier.id,...values(e.currentTarget)});await reloadSelected(rerender);}catch(ex){error=ex.message;rerender();}});
}
